version: '3'

services:
  # Start Zookeeper
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper-test
    ports:
      - "2181:2181"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
  # Start Kafka
  kafka:
    image: wurstmeister/kafka
    container_name: kafka-test
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: INTERNAL://:9093,EXTERNAL_SAME_HOST://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9093,EXTERNAL_SAME_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test_topic_1:1:1,test_topic_2:1:1"